<?php
/**
 * @var \Formax\Formularios\Block\Hipotecario\Comprobante $block
 */
?>
<?php
$dataForm  = $block->getFormData();
$baseMedia = $block->getBaseMediaDir();
$buttonLLink = $block->getButtonLink();
?>

<h1 class="simulator-title">Solicitud de Crédito de Consumo</h1>

<div class="simulator-container">
    <ol class="tabs" style="counter-reset: item 1;">
        <li ><span class="tab-title">Solicitud</span><span class="border border-left"></span></li>
        <li class="active"><span class="step">Paso 1/2</span><span class="tab-title">Comprobante</span><span class="border border-right"></span></li>
        <li class="step-wrapper"><span class="step">Paso 2/2</span><span class="border border-right"></span></li>
    </ol>
    <div class="voucher-content">
        <image class="Print-image" src="<?php echo $this->getViewFileUrl('Formax_SimulatorConsumo::images/logo-rojo.svg'); ?>"/>
        <div class="alerta-exito">
            <div class="content">
                <p class="title">Te contactaremos en breve</p>
            </div>
        </div>
        <div class="voucher-wrapper">
            <p class="voucher-title">Comprobante de simulación</p>
            <div class="simulator-voucher">
                <div class="simulator-result">
                    <table class="summary">
                        <tr>
                            <th scope="col">Monto Solicitado <small>(en pesos)</small></th>
                            <th scope="col">N° de cuotas</th>
                        </tr>
                        <tr class="big">
                            <td><?=$dataForm['monto']?></td>
                            <td><?=$dataForm['cuotas']?></td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <th scope="col">Fecha de simulación</th>
                            <th scope="col"><?=$dataForm['fecha']?></th>
                        </tr>
                        <tr>
                            <td>Valor cuota
                                <div class="coo-tooltip">
                                    <div class="tooltip-content">
                                        <p>Es el valor de cada uno de los pagos mensuales, con todos los gastos asociados al crédito.</p>
                                    </div>
                                </div>
                            </td>
                            <td><?=$dataForm['vcuota']?></td>
                        </tr>
                        <tr>
                            <td>Tasa de interés mensual</td>
                            <td><?=$dataForm['imensual']?></td>
                        </tr>
                        <tr>
                            <td>Tasa de interés anual</td>
                            <td><?=$dataForm['ianual']?></td>
                        </tr>
                        <tr>
                            <td>Seguro de desgravamen</td>
                            <td><?=$dataForm['desgravamen']?></td>
                        </tr>
                        <tr>
                            <td><span class="bold">Costo total del crédito</span> <span class="hide-mo">(en pesos)</span>
                                <div class="coo-tooltip">
                                    <div class="tooltip-content">
                                        <p>Es el monto total a pagar del préstamo, con todos los gastos y comisiones asociados.</p>
                                    </div>
                                </div>
                            </td>
                            <td class="bold"><?=$dataForm['total']?></td>
                        </tr>
                        <tr>
                            <td><span class="bold">CAE</span> <span class="hide-mo">(Carga anual equivalente)</span></td>
                            <td class="bold"><?=$dataForm['cae']?></td>
                        </tr>
                    </table>
                    
                </div>
                <div class="sello-coopeuch">
                    <img src="<?= $baseMedia . 'comprobante/sello-coopeuch.png' ?>" alt="Sello Coopeuch"/>
                </div>
            </div>
        </div>
        <div class="letra-pequena hipoteca">
    <p>(1) Para efectos de la simulación se incluyó el Seguro de Desgravamen, pero este seguro no es de carácter obligatorio

(2) La simulación de crédito de consumo que da cuenta esta hoja, requiere que el consumidor contratante disponga de un patrimonio y/o ingresos futuros suficientes para pagar su costo total y el valor cuota mensual, durante todo el período del crédito. Esta es sólo una simulación NO vinculante y el otorgamiento del crédito está sujeto a aprobación comercial previa, de acuerdo a las políticas de créditos vigentes al momento de la solicitud. El deudor podrá prepagar este crédito. Hay que considerar que en estos casos el socio deberá pagar una comisión sobre el capital que se prepaga asociada a esta operación, equivalente a 30 días de intereses calculado. Simulación válida sólo durante el día de su emisión, expirando en 24 horas. Los valores expresados en la presente simulación son referenciales y podrían variar al momento del curse.

</p>
</div>
</div>



<a href="<?= $block->getBaseUrl() ?>" class="semiBold link">&#60; Volver a Coopeuch</a>
