<div class="simulator-error-wrapper">
    <div class="simulator-error-wrapper-txt">
        <h1 class="h3 simulator-error-title">No pudimos recibir tu solicitud de crédito</h1>
        <p class="simulator-error-txt"><span class="semiBold block-txt">¿Qué puedes hacer? </span>Ahora mismo estamos revisando que pudo salir mal. Si gustas, puedes intentarlo más tarde.</p> 
        <a class="button-coopeuch" href="/">Volver al inicio</a>
    </div>
    <img class="simulator-error-img" src="<?php echo $this->getViewFileUrl('Formax_SimulatorConsumo::images/error.svg'); ?>" />
</div>
