<?php
/**
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="filter-current">
        <ol class="items">
            <span class="filter-label"><?= $block->escapeHtml(__('Results')) ?></span>
            <?php if ($block->getTotalRows() == 1):?>
                <?php $value = $block->getTotalRows() .' '. __('Product') ?>
            <?php else:?>
                <?php $value = $block->getTotalRows() .' '. __('Products') ?>
            <?php endif; ?>
            <span class="filter-value"><?= $block->escapeHtml($value) ?></span>
            <?php foreach ($_filters as $_filter): ?>
                <li class="item">
                    <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                    <span class="filter-value"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
                    <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    $filterName = __($_filter->getName()) . " " . $block->stripTags($_filter->getLabel());
                    if ($clearLinkUrl):
                        ?>
                        <a class="action previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
                            <span><?= $block->escapeHtml(__('Previous')) ?></span>
                        </a>
                        <a class="action remove"
                           title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                           href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                            <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    <?php else: ?>
                        <a class="action remove" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                           title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) ." ". $filterName ?>">
                            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
