<?php

/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Ceg\Analytics\ViewModel\AnalyticsData $viewModel
 */

$viewModel = $block->getAnalyticsViewModel();
$code = $viewModel->getConfig($block->getConfig());
if (!empty($code)) : ?>

    <!-- CEG | GOOGLE TAG MANAGER -->
    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', '<?=/* @noEscape */ $code ?>', 'auto');
    </script>

    <script type="text/x-magento-init">
        {
            "*": {
                "Ceg_Analytics/js/ceg_analytics": {
                    "credentials": "<?=/* @noEscape */ $code ?>",
                    "debug":  "<?=/* @noEscape */  $viewModel->isDebug() ?>",
                    "events":  <?= /* @noEscape */ $viewModel->getEventsConfig() ?>

                }
            }
        }
    </script>
    <!-- CEG | GOOGLE TAG MANAGER -->

<?php endif; ?>
