<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Ceg\Analytics\ViewModel\AnalyticsData $viewModel
 */
$viewModel = $block->getAnalyticsViewModel();
$code = $viewModel->getConfig($block->getConfig());
if (!empty($code)): ?>

<!-- CEG | GOOGLE TAG MANAGER -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?=  /* @noEscape */ $code ?>');</script>
<!-- CEG | GOOGLE TAG MANAGER -->

<?php endif;?>
