<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Ceg\Analytics\ViewModel\AnalyticsData $viewModel
 */
$viewModel = $block->getAnalyticsViewModel();
$code = $viewModel->getConfig($block->getConfig());
if (!empty($code)): ?>

<!-- CEG | HOTJAR -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:<?=  /* @noEscape */ $code ?>,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- CEG | HOTJAR -->

<?php endif; ?>
