<?php
/**
 * @var \Formax\Formularios\Block\Hipotecario\Index $block
 */
?>

<h1 class="simulator-title" style="margin-bottom: 5px;"><?= $block->getTitle() ?></h1>
<h2 class="regular text-download" style="margin-top: 0;"><?= $block->getTextDownload() ?></h2>

<div class="simulator-container">
    <ol class="tabs" style="counter-reset: item 0;">
        <li class="active"><span class="tab-title">Solicitud</span><span class="border border-left"></span></li>
        <li ><span class="step">Paso 1/2</span><span class="tab-title">Comprobante</span><span class="border border-right"></span></li>
        <li class="step-wrapper"><span class="step">Paso 2/2</span><span class="border border-right"></span></li>
    </ol>

    <div class="simulator-wrapper form-solicitud form-credit-card">

        <form id="cred-hipotecario" action="<?= $block->getUrl('solicitud/hipotecario/comprobante') ?>" method="POST" >
            <div class="modal-body three-colum-form">
                <div class="control">
                    <label for="name">Nombres</label>
                    <input type="text" name="name" class="form-input fm-field validate-text" maxlength="64">
                </div>
                <div class="control">
                    <label for="lastname">Apellidos</label>
                    <input type="text" name="lastname" class="form-input fm-field validate-text" maxlength="64">
                </div>
                <div class="field">
                    <div class="control">
                        <label for="rut">Rut</label>
                        <input name="rut" id="fm-rut" class="form-input fm-field" type="text" placeholder="Ej. 12.345.678-9" maxlength="12">
                    </div>
                </div>
                <div class="control">
                    <label for="phone">Teléfono</label>
                    <div class="phone-group">
                        <div class="coop-dropdown">
                            <div class="dropbtn form-input phonebtn"><span id="fm-code" class="main-prefix" data-value="9">9</span> <span class="coop-icon-down"></span></div>
                            <div id="dropdown-list" class="dropdown-content">
                                <div class="drop-item" data-value="9">9</div>
                                <div class="drop-item" data-value="6">6</div>
                                <div class="drop-item" data-value="7">7</div>
                                <div class="drop-item" data-value="8">8</div>
                                <div class="drop-item" data-value="2">2</div>
                                <div class="drop-item" data-value="32">32</div>
                                <div class="drop-item" data-value="33">33</div>
                                <div class="drop-item" data-value="34">34</div>
                                <div class="drop-item" data-value="35">35</div>
                                <div class="drop-item" data-value="41">41</div>
                                <div class="drop-item" data-value="42">42</div>
                                <div class="drop-item" data-value="43">43</div>
                                <div class="drop-item" data-value="45">45</div>
                                <div class="drop-item" data-value="51">51</div>
                                <div class="drop-item" data-value="52">52</div>
                                <div class="drop-item" data-value="53">53</div>
                                <div class="drop-item" data-value="55">55</div>
                                <div class="drop-item" data-value="57">57</div>
                                <div class="drop-item" data-value="58">58</div>
                                <div class="drop-item" data-value="61">61</div>
                                <div class="drop-item" data-value="63">63</div>
                                <div class="drop-item" data-value="64">64</div>
                                <div class="drop-item" data-value="65">65</div>
                                <div class="drop-item" data-value="67">67</div>
                                <div class="drop-item" data-value="71">71</div>
                                <div class="drop-item" data-value="72">72</div>
                                <div class="drop-item" data-value="73">73</div>
                                <div class="drop-item" data-value="75">75</div>
                            </div>
                        </div>
                        <input type="hidden" id="prefix" name="code" value="9"/>
                        <input type="tel"  id="fm-phone" name="phone" class="form-input phone fm-field digit" maxlength="8">
                    </div>
                </div>
                <div class="control">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-input fm-field" maxlength="64">
                </div>
                <div class="control">
                    <label for="monthly-income">Ingreso líquido mensual</label>
                    <input type="tel" class="form-input fm-field digit money" id="monthly-income" name="monthly-income" value="$">
                </div>
            </div>

            <hr/>
            <div class="modal-body three-colum-form">
                <div class="control">
                    <label for="amount">Valor propiedad</label>
                    <input type="tel" class="form-input fm-field digit money" id="amount" name="amount" value="$">
                </div>
                <div class="control">
                    <label for="email">¿Tienes el 20% del pie?</label>
                    <div class="lower-dividend">
                        <div class="checkbox-group">
                            <div class="checkbox-flex" style="margin-bottom: 10px">
                                <input type="checkbox" id="check-down-payment-yes" class="check-down-payment" name="check-down-payment-yes">
                                <label for="check-down-payment-yes">Si</label>
                            </div>
                            <div class="checkbox-flex">
                                <input type="checkbox" id="check-down-payment-no" class="check-down-payment" name="check-down-payment-no">
                                <label for="check-down-payment-no">No</label>
                            </div>
                        </div>
                        <input type="tel" class="form-input fm-field digit money" id="down-payment" name="down-payment" placeholder="Ingresa el monto en pesos">
                    </div>
                </div>
            </div>

            <div class="field container-submit">
                <div class="control button">
                    <input id="sub-cred-hipotecario" class="button-coopeuch send-form"  type="submit" value="Solicitar" />
                </div>
            </div>
        </form>
    </div>
</div>
<div class="letra-pequena hipoteca">
    <p><?= $block->getLegalTerms() ?></p>
</div>
<a href="<?= $block->getBaseUrl() ?>" class="semiBold link">&#60; Volver a Coopeuch</a>

<script type="text/x-magento-init">
{
    "*": {
        "validate-form": {}
    }
}
</script>