<?php
/**
 * @var \Ceg\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
$menuItemStoreId = "menu-item-store";
$menuItemBillingId = "menu-item-billing";
$menuItemOrdersId = "menu-item-orders";
?>
<?php if ($block->getShowPart() == 'welcome'): ?>
<li class="apps" data-action="navigation" data-mage-init='{"dropdown":{}}' data-toggle="apps-dropdown">
    <?=  /* @noEscape */ __('Access'); ?>
    <button type="button"
            class="action switch"
            tabindex="-1"
            data-action="apps-menu-toggle">
        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
            <path d="M0 0h24v24H0z" fill="none"/>
            <path d="M4 8h4V4H4v4zm6 12h4v-4h-4v4zm-6 0h4v-4H4v4zm0-6h4v-4H4v4zm6 0h4v-4h-4v4zm6-10v4h4V4h-4zm-6
            4h4V4h-4v4zm6 6h4v-4h-4v4zm0 6h4v-4h-4v4z"/>
        </svg>
    </button>
    <ul id=apps-menu" class="apps-menu" data-target="apps-dropdown">
        <li class="level0 ">
            <a class="level-top <?=  /* @noEscape */ $menuItemStoreId ?>"
               href="<?= /* @noEscape */ $block->getStoreURL(); ?>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none"/>
                    <path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35
                    2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14
                    0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48
                    0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"/>
                </svg>
                <span><?= /* @noEscape */ $block->getStoreTitle(); ?></span>
            </a>
        </li>
        <li class="level0 level-top ui-menu-item">
            <a class="level-top <?= /* @noEscape */ $menuItemBillingId ?>"
               href="<?= /* @noEscape */ $block->getBillingURL(); ?>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none"/>
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1.41
                    16.09V20h-2.67v-1.93c-1.71-.36-3.16-1.46-3.27-3.4h1.96c.1 1.05.82 1.87 2.65 1.87 1.96 0
                    2.4-.98 2.4-1.59 0-.83-.44-1.61-2.67-2.14-2.48-.6-4.18-1.62-4.18-3.67 0-1.72 1.39-2.84
                    3.11-3.21V4h2.67v1.95c1.86.45 2.79 1.86 2.85 3.39H14.3c-.05-1.11-.64-1.87-2.22-1.87-1.5
                    0-2.4.68-2.4 1.64 0 .84.65 1.39 2.67 1.91s4.18 1.39 4.18 3.91c-.01 1.83-1.38 2.83-3.12 3.16z"/>
                </svg>
                <span><?= /* @noEscape */ $block->getBillingTitle(); ?></span>
            </a>
        </li>
        <li class="level0 level-top ui-menu-item">
            <a class="level-top <?= /* @noEscape */ $menuItemOrdersId ?>"
               href="<?= /* @noEscape */ $block->getOrdersURL(); ?>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none"/>
                    <path d="M19 3h-4.18C14.4 1.84 13.3 1 12 1c-1.3 0-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2
                    2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 0c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zm2
                    14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z"/>
                </svg>
                <span><?= /* @noEscape */ $block->getOrdersTitle(); ?></span>
            </a>
        </li>
    </ul>
</li>
<li class="greet welcome" data-bind="scope: 'customer'">
    <!-- ko if: customer().firstname  -->
    <span class="logged-in"
          <?php $value = __('Hello, %1!', '%1'); ?>
          data-bind="text: new String('<?= $block->escapeHtml($value) ?>').replace('%1', customer().firstname)">
    </span>
    <!-- /ko -->
</li>
<script type="text/x-magento-init">
{
    "#apps-menu": {
        "menu": {
            "responsive": false,
            "expanded": false,
            "position": {
                "my": "left bottom",
                "at": "left bottom"
            }
        }
    },
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        },
        "Ceg_Theme/js/headerhandler": {
            "menuItemStore": {
                "selector": ".<?= /* @noEscape */ $menuItemStoreId ?>",
                "target": "_self"
            },
            "menuItemBilling": {
                "selector": ".<?= /* @noEscape */ $menuItemBillingId ?>",
                "target": "_blank"
            },
            "menuItemOrders": {
                "selector": ".<?= /* @noEscape */ $menuItemOrdersId ?>",
                "target": "_blank"
            }
        }
    }
}
</script>
<?php elseif ($block->getShowPart() == 'other'):?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
